# Generated by Django 3.2.16 on 2022-11-16 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breadth',
            fields=[
                ('BreadthId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('BreadthName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=16)),
                ('CourseCategoryId', models.IntegerField()),
                ('CourseTitle', models.CharField(max_length=128)),
                ('CourseDescription', models.TextField()),
                ('CourseCredits', models.CharField(max_length=8)),
                ('CourseReferenceId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExampleMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['message'],
            },
        ),
        migrations.CreateModel(
            name='GenEd',
            fields=[
                ('GenEdId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('GenEdName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('MajorId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('MajorName', models.CharField(max_length=128)),
                ('MajorShortName', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('ProfessorId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('ProfessorName', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('UserEmail', models.CharField(max_length=256)),
                ('UserPassword', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('SectionId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapi.course')),
                ('Professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapi.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SemesterCode', models.IntegerField()),
                ('SemesterName', models.CharField(max_length=16)),
                ('Gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('GradeCountA', models.IntegerField()),
                ('GradeCountAb', models.IntegerField()),
                ('GradeCountB', models.IntegerField()),
                ('GradeCountBc', models.IntegerField()),
                ('GradeCountC', models.IntegerField()),
                ('GradeCountD', models.IntegerField()),
                ('GradeCountF', models.IntegerField()),
                ('GradeCountSd', models.IntegerField()),
                ('GradeCountUd', models.IntegerField()),
                ('GradeCountOther', models.IntegerField()),
                ('GradeCountTotal', models.IntegerField()),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapi.section')),
            ],
        ),
        migrations.CreateModel(
            name='GenEdBridge',
            fields=[
                ('GBId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapi.course')),
                ('GenEd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapi.gened')),
            ],
        ),
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseLevel', models.CharField(max_length=32)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapi.course')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('CommentId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('ParentId', models.IntegerField()),
                ('CommentContent', models.TextField()),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapi.section')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='BreadthBridge',
            fields=[
                ('BBId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Breadth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapi.breadth')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapi.course')),
            ],
        ),
    ]
