# Generated by Django 3.2.16 on 2022-11-16 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('EnrollmentId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapi.course')),
                ('Major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapi.major')),
            ],
        ),
    ]
